# Generated by Django 4.1.1 on 2022-09-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='secondaryT_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectcode', models.CharField(max_length=100)),
                ('question_label', models.CharField(max_length=100)),
                ('quantative_ans', models.CharField(max_length=100)),
                ('qualitative_ans', models.CharField(max_length=100)),
            ],
        ),
    ]
