# Generated by Django 4.1.1 on 2022-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectcode', models.CharField(max_length=100)),
                ('methodplogy', models.CharField(max_length=100)),
                ('geoscope', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('pobjective', models.CharField(max_length=100)),
                ('subjectsep', models.CharField(max_length=100)),
                ('sme', models.CharField(max_length=100)),
                ('raudience', models.CharField(max_length=100)),
                ('analyst', models.CharField(max_length=100)),
                ('dataanalyst', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='project_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=50)),
                ('file', models.FileField(default=None, max_length=250, null=True, upload_to='file/')),
            ],
        ),
    ]
